name: Flutter Analyze and Test

on:
  push:
    branches: [ '**' ]
  pull_request:
    branches: [ main, develop ]

jobs:
  analyze-and-test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.32.5
          channel: stable
          
      - name: Install dependencies
        run: |
          flutter pub get
          
      - name: Generate code
        run: |
          flutter pub run build_runner build --delete-conflicting-outputs
        
      - name: Analyze code
        run: flutter analyze lib

      - name: Run tests
        run: flutter test
